language: python
dist: xenial

python:
  - 3.6
  - 3.7

install:
  - pip install poetry
  - poetry install

script:
  - poetry run flake8 .
  - poetry run pytest
  - poetry run mypy flake8_broken_line.py

after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: change
